Update main_webapp-ocr-p7.yml

diff --git a/.github/workflows/main_webapp-ocr-p7.yml b/.github/workflows/main_webapp-ocr-p7.yml
--- a/.github/workflows/main_webapp-ocr-p7.yml
+++ b/.github/workflows/main_webapp-ocr-p7.yml
@@ -24,18 +24,38 @@ jobs:
         with:
           python-version: '3.11'
 
+      - name: Check requirements.txt
+        run: |
+          if [ ! -f "requirements.txt" ]; then
+            echo "Error : requirements.txt not found !"
+            exit 1
+          fi
       - name: Create and start virtual environment
         run: |
           python -m venv venv
           source venv/bin/activate
       
       - name: Install dependencies
-        run: pip install -r requirements.txt
+        run: |
+          pip install --upgrade pip
+          pip install -r requirements.txt
+          pip install pytest httpx pytest-asyncio
+      - name: Start FastAPI Server
+        run: |
+          uvicorn main:app --host 0.0.0.0 --port 8000 &
+          sleep 5
+      - name: Run Tests with Pytest
+        run: |
+          pytest tests/ --asyncio-mode=auto
+     
+      - name: Stop FastAPI Server
+        run: |
+          pkill -f uvicorn || true
         
       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
 
       - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+        run: zip -r release.zip ./* -x "**venv**/*" "**__pycache__**/*"
 
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v4
@@ -44,7 +64,6 @@ jobs:
           path: |
             release.zip
             !venv/
-
   deploy:
     runs-on: ubuntu-latest
     needs: build
@@ -68,9 +87,9 @@ jobs:
       - name: Login to Azure
         uses: azure/login@v2
         with:
-          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB26B2FE303546F8AABBEDD87FF9FB3D }}
-          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_79055DF092CE44B69290DDE1ED6D7AC9 }}
-          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_93BDB21A9B2243A7BFED90B409B0ED28 }}
+          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D6CC4BD5D4EE47358B31F73369717405 }}
+          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ECEE0A24FA534258AC42EBBA15123547 }}
+          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D1A5FFF855CE4167B740ED69A85C7579 }}
 
       - name: 'Deploy to Azure Web App'
         uses: azure/webapps-deploy@v3
@@ -78,4 +97,6 @@ jobs:
         with:
           app-name: 'webapp-ocr-p7'
           slot-name: 'Production'
+          package: ./release.zip
+          runtime-stack: "PYTHON|3.11"
           
