Update main_webapp-ocr-p7.yml

diff --git a/.github/workflows/main_webapp-ocr-p7.yml b/.github/workflows/main_webapp-ocr-p7.yml
--- a/.github/workflows/main_webapp-ocr-p7.yml
+++ b/.github/workflows/main_webapp-ocr-p7.yml
@@ -24,6 +24,13 @@ jobs:
         with:
           python-version: '3.11'
 
+      - name: Check requirements.txt
+        run: |
+          if [ ! -f "requirements.txt" ]; then
+            echo "Error : requirements.txt not found !"
+            exit 1
+          fi
+
       - name: Create and start virtual environment
         run: |
           python -m venv venv
@@ -31,6 +38,7 @@ jobs:
       
       - name: Install dependencies
         run: |
+          pip install --upgrade pip
           pip install -r requirements.txt
           pip install pytest httpx pytest-asyncio
 
@@ -50,7 +58,7 @@ jobs:
       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
 
       - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+        run: zip -r release.zip ./* -x "**venv**/*" "**__pycache__**/*"
 
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v4
@@ -93,4 +101,6 @@ jobs:
         with:
           app-name: 'webapp-ocr-p7'
           slot-name: 'Production'
+          package: ./release.zip
+          runtime-stack: "PYTHON|3.11"
           
